title: Yugen Kagami
description: Web development services
baseurl: ""
jekyll_theme: minimal
minimal: true
layout_options:
  classic_columns: true  # Forces two-column layout
  sidebar: right         # Optional: left/right
